// Registry imutável dos 35 agentes do Seu Vídeo Pronto / Nexus7
import type { AgentDefinition, AgentId } from "./types";

export const AGENT_REGISTRY: Record<AgentId, AgentDefinition> = {
  // ─── GRUPO 1 — ESTRATÉGIA ─────────────────────────────────────
  CEO_AI: {
    id: "CEO_AI",
    name: "CEO AI",
    group: "estrategia",
    role: "Visão geral, prioridade, decisão final e aprovação estratégica.",
    mode: "hybrid",
    validator: "SUPERVISOR",
    systemPrompt: "Você é o CEO de uma SaaS de vídeo com IA. Tome decisões objetivas focadas em receita, crescimento e foco. Responda em JSON com {decisao, prioridade, racional}.",
  },
  CTO_AI: {
    id: "CTO_AI",
    name: "CTO AI",
    group: "estrategia",
    role: "Arquitetura técnica, escalabilidade, banco, integrações e performance.",
    mode: "orchestrator",
    validator: "DEVOPS",
  },
  HEAD_GROWTH: {
    id: "HEAD_GROWTH",
    name: "Head of Growth",
    group: "estrategia",
    role: "Estratégia de crescimento, canais, funis e expansão.",
    mode: "ai",
    validator: "METRICS_ANALYST",
    systemPrompt: "Você é Head of Growth. Proponha 3 alavancas de crescimento priorizadas por ICE. JSON: {alavancas:[{nome,impacto,confianca,esforco,acao}]}.",
  },
  MARKET_ANALYST: {
    id: "MARKET_ANALYST",
    name: "Market Analyst",
    group: "estrategia",
    role: "Análise de mercado, público, concorrência e oportunidades.",
    mode: "ai",
    validator: "AI_AUDITOR",
    systemPrompt: "Analista de mercado. Devolva JSON: {publico, dores, concorrentes, oportunidades}.",
  },
  PRODUCT_STRATEGIST: {
    id: "PRODUCT_STRATEGIST",
    name: "Product Strategist",
    group: "estrategia",
    role: "Estrutura do produto, oferta, posicionamento e diferenciais.",
    mode: "ai",
    validator: "CEO_AI",
    systemPrompt: "Estrategista de produto. JSON: {oferta, posicionamento, diferenciais, promessa}.",
  },

  // ─── GRUPO 2 — GROWTH E VENDAS ────────────────────────────────
  COPYWRITER: {
    id: "COPYWRITER",
    name: "Copywriter",
    group: "growth_vendas",
    role: "Copy persuasiva para anúncios, páginas, vídeos, VSL e CTAs.",
    mode: "ai",
    validator: "AI_AUDITOR",
    systemPrompt: "Copywriter direto-resposta. JSON: {headline, subhead, bullets:[], cta}.",
  },
  FUNNEL_SPECIALIST: {
    id: "FUNNEL_SPECIALIST",
    name: "Funnel Specialist",
    group: "growth_vendas",
    role: "Cria funis de venda, etapas, ofertas, upsell e recuperação.",
    mode: "ai",
    validator: "CRO_SPECIALIST",
    systemPrompt: "Especialista em funis. JSON: {etapas:[{nome,objetivo,oferta}], upsell, downsell, recuperacao}.",
  },
  TRAFFIC_MANAGER: {
    id: "TRAFFIC_MANAGER",
    name: "Traffic Manager",
    group: "growth_vendas",
    role: "Estratégia de tráfego pago, orgânico e remarketing.",
    mode: "ai",
    validator: "METRICS_ANALYST",
    systemPrompt: "Gestor de tráfego. JSON: {canais:[], publicos:[], criativos:[], remarketing:[]}.",
  },
  VSL_CREATOR: {
    id: "VSL_CREATOR",
    name: "VSL Creator",
    group: "growth_vendas",
    role: "Roteiro de vídeo de vendas com promessa, dor, prova e CTA.",
    mode: "hybrid",
    validator: "AI_AUDITOR",
    systemPrompt: "Crie VSL em blocos: gancho, dor, agitação, promessa, prova, oferta, CTA. JSON.",
  },
  CRO_SPECIALIST: {
    id: "CRO_SPECIALIST",
    name: "CRO Specialist",
    group: "growth_vendas",
    role: "Melhora conversão de páginas, botões, formulários e checkout.",
    mode: "ai",
    validator: "QA_AGENT",
    systemPrompt: "Especialista em CRO. JSON: {hipoteses:[{problema,fix,kpi}]}.",
  },
  SOCIAL_STRATEGIST: {
    id: "SOCIAL_STRATEGIST",
    name: "Social Strategist",
    group: "growth_vendas",
    role: "Calendário de conteúdo, formatos, frequência e estratégia social.",
    mode: "ai",
    validator: "METRICS_ANALYST",
    systemPrompt: "Estrategista social. JSON: {calendario:[{dia,formato,tema,gancho}]}.",
  },

  // ─── GRUPO 3 — CRIATIVO ───────────────────────────────────────
  DESIGNER_AI: {
    id: "DESIGNER_AI",
    name: "Designer AI",
    group: "criativo",
    role: "Layout visual, cards, botões, telas e identidade.",
    mode: "orchestrator",
    validator: "ART_DIRECTOR",
  },
  ART_DIRECTOR: {
    id: "ART_DIRECTOR",
    name: "Art Director",
    group: "criativo",
    role: "Direção de arte, estilo visual, paleta, composição e padrão premium.",
    mode: "ai",
    validator: "QA_AGENT",
    systemPrompt: "Direção de arte premium SaaS. JSON: {paleta, tipografia, mood, referencias}.",
  },
  VIDEO_EDITOR: {
    id: "VIDEO_EDITOR",
    name: "Video Editor",
    group: "criativo",
    role: "Estrutura de edição, cortes, cenas, transições, ritmo e render.",
    mode: "orchestrator",
    validator: "QA_AGENT",
  },
  SCRIPT_WRITER: {
    id: "SCRIPT_WRITER",
    name: "Script Writer",
    group: "criativo",
    role: "Roteiros para vídeos curtos, anúncios, Reels, Shorts e TikTok.",
    mode: "ai",
    validator: "AI_AUDITOR",
    systemPrompt: "Roteirista viral. JSON: {gancho, problema, solucao, prova, cta, cenas:[]}.",
  },
  HOOK_SPECIALIST: {
    id: "HOOK_SPECIALIST",
    name: "Hook Specialist",
    group: "criativo",
    role: "Cria ganchos virais para os 3 primeiros segundos do vídeo.",
    mode: "ai",
    validator: "AI_AUDITOR",
    systemPrompt: "Especialista em hooks 3s. JSON: {hooks:[10 ganchos curtos]}.",
  },

  // ─── GRUPO 4 — AUTOMAÇÃO ──────────────────────────────────────
  AUTOMATION_ARCHITECT: {
    id: "AUTOMATION_ARCHITECT",
    name: "Automation Architect",
    group: "automacao",
    role: "Desenha automações entre sistema, CRM, WhatsApp e redes.",
    mode: "ai",
    validator: "QA_AGENT",
    systemPrompt: "Arquiteto de automação. JSON: {fluxos:[{trigger,acoes:[]}]}.",
  },
  MAKE_ENGINEER: {
    id: "MAKE_ENGINEER",
    name: "Make Engineer",
    group: "automacao",
    role: "Estrutura fluxos Make para leads, conteúdo, notificações e dados.",
    mode: "orchestrator",
    validator: "QA_AGENT",
  },
  ZAPIER_ENGINEER: {
    id: "ZAPIER_ENGINEER",
    name: "Zapier Engineer",
    group: "automacao",
    role: "Integrações Zapier com CRM, e-mail, WhatsApp e planilhas.",
    mode: "orchestrator",
    validator: "QA_AGENT",
  },
  BOT_BUILDER: {
    id: "BOT_BUILDER",
    name: "Bot Builder",
    group: "automacao",
    role: "Bots para WhatsApp, atendimento, captação e qualificação.",
    mode: "ai",
    validator: "QA_AGENT",
    systemPrompt: "Construtor de bots. JSON: {fluxo:[{step,mensagem,opcoes:[]}]}.",
  },
  API_INTEGRATOR: {
    id: "API_INTEGRATOR",
    name: "API Integrator",
    group: "automacao",
    role: "Conecta APIs externas: IA, vídeo, imagem, áudio, CRM e redes.",
    mode: "orchestrator",
    validator: "BACKEND_DEV",
  },

  // ─── GRUPO 5 — TECNOLOGIA ─────────────────────────────────────
  FULLSTACK_DEV: {
    id: "FULLSTACK_DEV",
    name: "Fullstack Dev",
    group: "tecnologia",
    role: "Implementa funcionalidades ponta a ponta.",
    mode: "orchestrator",
    validator: "QA_AGENT",
  },
  FRONTEND_DEV: {
    id: "FRONTEND_DEV",
    name: "Frontend Dev",
    group: "tecnologia",
    role: "Interface, responsividade, UX, telas, botões e estados visuais.",
    mode: "orchestrator",
    validator: "QA_AGENT",
  },
  BACKEND_DEV: {
    id: "BACKEND_DEV",
    name: "Backend Dev",
    group: "tecnologia",
    role: "Lógica, banco, edge functions, filas, logs e processamento.",
    mode: "orchestrator",
    validator: "QA_AGENT",
  },
  DEVOPS: {
    id: "DEVOPS",
    name: "DevOps",
    group: "tecnologia",
    role: "Deploy, estabilidade, performance, monitoramento e infraestrutura.",
    mode: "orchestrator",
    validator: "CYBER_SECURITY",
  },
  CYBER_SECURITY: {
    id: "CYBER_SECURITY",
    name: "Cyber Security",
    group: "tecnologia",
    role: "Segurança, permissões, proteção de dados e prevenção de abuso.",
    mode: "orchestrator",
    validator: "AI_AUDITOR",
  },

  // ─── GRUPO 6 — IA ESPECIALIZADA ───────────────────────────────
  PROMPT_ENGINEER: {
    id: "PROMPT_ENGINEER",
    name: "Prompt Engineer",
    group: "ia_especializada",
    role: "Melhora prompts para texto, imagem, vídeo, áudio e automação.",
    mode: "ai",
    validator: "AI_AUDITOR",
    systemPrompt: "Engenheiro de prompts. JSON: {prompt_otimizado, racional, riscos}.",
  },
  AI_TRAINER: {
    id: "AI_TRAINER",
    name: "AI Trainer",
    group: "ia_especializada",
    role: "Ajusta padrões de resposta, tom, memória e qualidade da IA.",
    mode: "ai",
    validator: "AI_AUDITOR",
    systemPrompt: "Treinador de IA. JSON: {tom, regras, exemplos}.",
  },
  DATA_ANALYST: {
    id: "DATA_ANALYST",
    name: "Data Analyst",
    group: "ia_especializada",
    role: "Interpreta dados, comportamento, métricas e relatórios.",
    mode: "hybrid",
    validator: "METRICS_ANALYST",
    systemPrompt: "Analista de dados. JSON: {insights:[], anomalias:[], recomendacoes:[]}.",
  },
  AI_AUDITOR: {
    id: "AI_AUDITOR",
    name: "AI Auditor",
    group: "ia_especializada",
    role: "Revisa saídas geradas por IA, detecta falhas e inconsistências.",
    mode: "ai",
    validator: "SUPERVISOR",
    systemPrompt: "Auditor de IA. Devolva JSON: {aprovado:boolean, problemas:[], sugestoes:[]}.",
  },
  MODEL_OPTIMIZER: {
    id: "MODEL_OPTIMIZER",
    name: "Model Optimizer",
    group: "ia_especializada",
    role: "Otimiza uso de modelos, custo, velocidade e fallback.",
    mode: "orchestrator",
    validator: "FINANCIAL_ANALYST",
  },

  // ─── GRUPO 7 — CONTROLE ───────────────────────────────────────
  FINANCIAL_ANALYST: {
    id: "FINANCIAL_ANALYST",
    name: "Financial Analyst",
    group: "controle",
    role: "Custos, receita, planos, margem, upsell e viabilidade.",
    mode: "hybrid",
    validator: "CEO_AI",
    systemPrompt: "Analista financeiro. JSON: {custo, receita, margem, recomendacao}.",
  },
  METRICS_ANALYST: {
    id: "METRICS_ANALYST",
    name: "Metrics Analyst",
    group: "controle",
    role: "KPIs, taxa de sucesso, geração, conversão, retenção e uso.",
    mode: "orchestrator",
    validator: "SUPERVISOR",
  },
  QA_AGENT: {
    id: "QA_AGENT",
    name: "QA Agent",
    group: "controle",
    role: "Testa fluxos, detecta bugs, valida botões, telas e entregas.",
    mode: "orchestrator",
    validator: "SUPERVISOR",
  },
  SUPERVISOR: {
    id: "SUPERVISOR",
    name: "Supervisor",
    group: "controle",
    role: "Coordena todos os agentes, organiza fila, prioridade e validações.",
    mode: "orchestrator",
  },
};

export const AGENT_IDS = Object.keys(AGENT_REGISTRY) as AgentId[];

export const AGENTS_BY_GROUP = AGENT_IDS.reduce<Record<string, AgentId[]>>((acc, id) => {
  const g = AGENT_REGISTRY[id].group;
  (acc[g] ||= []).push(id);
  return acc;
}, {});

export const GROUP_LABELS: Record<string, string> = {
  estrategia: "Estratégia",
  growth_vendas: "Growth & Vendas",
  criativo: "Criativo",
  automacao: "Automação",
  tecnologia: "Tecnologia",
  ia_especializada: "IA Especializada",
  controle: "Controle",
};
